BUF_TOKEN: ENC[AES256_GCM,data:BbEcJKQFjwZeLRslWl1xKrPaaJQRhayTRlP1pxAgpIV7cbyqCw1Q9CH6Xz8hILkjTdwcMHS+KqnzUZWUvklb6A==,iv:s2I3eORaIjZaxNeYmodQTRQsrAcWlH9QwPlLe+kzb7E=,tag:UTlN+YRMm6L7omwM8Usx9g==,type:str]
sops:
  lastmodified: "2026-09-14T07:20:27Z"
  mac: ENC[AES256_GCM,data:vOVj/TkTNvZxPb9L50x3npnlUYsH/EGscRjpeOHG+csYjpRGn8eqTI7XyoYdN98wVKho2NNYoYn0LK1ZGYGd/6Pwb7ZSXRab4LAXsLXVJlmAF9NvjbC93bb/fFX1JwpptWkqWV6casQUNvHoBi1BfTIZP1nZd4Pr8Bbv6aZzWgs=,iv:leOZTDiqIdHZOvsQVaqSn+Z+lfln3Dop6siseFT+/eY=,tag:q7masb0YMaFgr2gsWVeggQ==,type:str]
  pgp:
    - created_at: "2026-09-14T07:20:27Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxYgP05NwJ3CAQ//TyXatjaf5UXyvFuv8XF6w7QKnRRez5Z2f82/LbR+M5D3
        q1iwkP5GPyBMg1vtHsSYag78/b61FP4iAu1s2weI/YjzAybQu5UJdXrIS8Okixfv
        gmrXh312iNg6gKL+OQyopCGo37XmKqH7yOCnVbwnXzt9VfDF56Qm4YqRnSvCtqu2
        fENss7YBazHn2yqQ0GIBOtYl4tlYXN0e+gTUJ0ib9+37tn5SO7tMI7qA1TThSCYc
        qaLFsFW1fTxmRJxGm415l0M0SvUYvlNtIvV8zWLgDYdcAhcVZxUZAvsVoKzwL/CV
        eKv4TdiyQXABtDzrUKPBcqW9W0CZ2prVPe/0c8Z9Ka2vobJ8ZBM/BxHDg0WjKIy7
        M3LZryhvQla/WMsF1+lO0FMBbmQFV7Aqo4Qx/uR2xDBl/iKMa+EaQkvXvfhJBcNh
        k6umEnTDpT/hpg3WstANGy7tco9P2KfRXy41SrT7j67cLKJeak3E3CM+xR7PydNI
        NHdL0x3ZrvtLp0Zg8UHhskikaSkNe17H/344rE93FT872byI/7k+N+TkGE1b/VSV
        E1j2K/22L9n4/DWp1htp82cChlb2e2zL2uKHBr6S5wEVPMo7BmDobTW4rQK83m0T
        QYxtPN8SPVK8hhwRt0GFAYwSBi1ne1Gh376gHWw9mW4Jrj1NvCghwHnnok/asBbU
        aAEJAhAW1a1avHkfnNsb1JpnpZeqS98gujPCVBDuRAEDVSkOyUimNOcJ5iRIvmH+
        gkOfqL/oYMY07AaogPn2LrAq5u/03EbG8Vl3/4rrAz9BYmBCcxWImdkD4U5IdeoS
        5UFooVFpSDeS
        =mLdK
        -----END PGP MESSAGE-----
      fp: 311A18B60972303C558FFC6C9BA7DE47D7C15C96
    - created_at: "2026-09-14T07:20:27Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7m5W8M9NGm2ARAAhzGbrWp0mSPSqopI2ZJNopYmBjPWN+hXEcKwTWxUoPEz
        RwaD1FHEtXmcifRHW3xqS/DD5qRu8q+yl3jLub7+Go7BY0QvxkrMxXGN/tl3xmrq
        eAUGBvgv3iIJf49Xbb8vmbkP2h+f+X65vvPokNaMjSi5MXd+aSzotdBvm2Rc0dS/
        mCq58NRyK8W8PoqD5QzpumHEWVgiKiV+GJUM+LI1CfW9DW+VlZGHptxljcqKvT/u
        WtumAqSDLNlT+WJYVnr+vLI0ym9W3bcZKle4eDCVpkabJCrnAnjBxWbdyzR3qW2c
        j2+Ta6Wjg/alNoHGU/VgYP0tArCWgBuFy7u/9Udaw027cHiLl0Sp2hdD00ZK5x3E
        RlC1jIPwiaj70v4xw2HJQ/xQL/9HX9rRTBmrgb7KytSD73gyXuGTGbo5DSDhs3+2
        qMoit/glbdmbs7/OSiX8h9thDo9hR0w5KpyzYEZntWv9F+yoy3DyMAq6+D/G7nvd
        TYjy3oc4dS0ZT1OKcBxuQ19gPnlZizx94ct+XVY3Weax46A3MDGRmt5udlip7sLi
        Xlf/gS8LfcpQGGuIftd15TOhmPFFi/qNA5Pd8ZWZXLFNvZh0vCwg43xonG+yqYeS
        UiOK3UTbI4ji+g9Sx4o26p328V7YX5HdlLyeWeK4L9P8OidM9qysYhWoDPglkefU
        aAEJAhDs5SNKCDl0wvZ0TIxm+uED1FrD/Zm5HRZJ1rfA5sbUY5N1gZDCD7Gr3Fxn
        Yv2CoP4bXWOU+ncqUh+5mHn3N+0B3Zrs9qmTuDQZ3zRKLCoQoFT4DV1E/2e39iru
        K5iIbhMWwmeV
        =tFao
        -----END PGP MESSAGE-----
      fp: 8152B0C0997AA5D37F6E112CE7C5A614030CCC00
  unencrypted_suffix: _unencrypted
  version: 3.13.3
