# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: CI
run-name: Running continuous integration on ${{ github.actor }}'s commits

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup pipeline
        uses: ./.github/composite/setup

      - name: Cache Bun dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install deps
        shell: bash
        run: bun install --frozen-lockfile

      - name: Run Tests
        run: bun run test

  preview:
    name: Preview Pulumi changes
    needs: [test]
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Pipeline
        uses: ./.github/composite/setup
        with:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          INSTALL_SOPS: true

      - name: Cache Bun dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run Pulumi Preview
        run: bun run .github/scripts/src/pulumi/preview --prId=${{ github.event.number }}

  createTag:
    name: Create new tag
    runs-on: ubuntu-latest
    needs: [test]

    if: github.ref_name == 'main'

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup pipeline
        uses: ./.github/composite/setup
        with:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          INSTALL_SOPS: true

      - name: Create new tag
        uses: ./.github/composite/create-tag
